### ISSUE TITLE
Python version installation error

### ISSUE THREAD

**Issue by ammaralsheik** [compugen-ltd/supercells#1]
I'm having issues and wasn't able to install the package. I'm getting error about requiring python version 3.6.10 when i try to install from wheel file. Also the pip install command doesn't work:
ERROR: Could not find a version that satisfies the requirement supercells (from versions: none)
ERROR: No matching distribution found for supercells

**Comment by royassis** [comment]
Hey @ammaralsheik can you copy paste the pip command + the python version you are using .

**Comment by ammaralsheik** [comment]
Hi Roy, thanks for your response, seems that the issue has been resolved for me using Python 3.10.5 "pip install supercells" worked and I was able to run the command to generate summary table! Looking forward to more functionality if that's coming in the future, definitely valuable!

**Comment by royassis** [comment]
@ammaralsheik Great ! Glad that you resolved the issue, and thank you for the feedback. @rgranit Is the repo publisher I'm sure he appreciates this as well.
